<!-- Holds a php variable that changes the title of the page -->
<?php $pageTitle = "Jaxon's Jewlery"; ?>
<title><?php echo $pageTitle; ?></title>
<header>
  <h1>Jaxon'sJewelry</h1>
  <nav>
    <ul>
      <li><a href="jaxonsHome.php">Home</a></li>
      <li><a href="products.php">Products</a></li>
      <li><a href="about.php">About Us</a></li>
      <li><a href="contact.php">Contact</a></li>
      <li><a href="events.php">Events</a></li>
    </ul>
  </nav>
</header>
