/*** Page Styles ***/ body{ max-width: 1400px; margin: auto; } main{ max-width:
1300px; margin: auto; text-align: center; } p{ font-size: 20px; font-family:
sans-serif; } span{ font-size: 18px; } /*** Header Styles ***/ header{
border-bottom: black 3px solid; margin-bottom: 10px; } h1{ text-align: center;
font-size: 64px; font-family: "Yellowtail", sans-serif; font-weight: 700; color:
navy; } h3{ text-align: center; font-size: 30px; font-family: "Yellowtail",
sans-serif; color: navy; } h4{ text-align: center; font-size: 25px; font-family:
"Yellowtail", sans-serif; color: navy; } nav { text-align: center; font-family:
sans-serif; } nav ul { list-style: none; display: inline-block; } nav li {
display: inline-block; text-align: center; font-size: 25px; padding: 10px; }
a:link { text-decoration: none; padding-bottom: 10px; padding-top: 10px;
padding-left: 25px; padding-right: 25px; color: navy; } a:visited { color: blue;
} a:hover { color: b; background-color: #cfcfcf; } /*** Footer Styles ***/
footer{ border-top: black 3px solid; text-align: center; font-size: 18px;
font-family: sans-serif; margin-top: 20px; } /*** Home Page Styles ***/
.homeHeader{ background-image: url("images/assortedJewelry_cropped.jpg");
margin-left: auto; margin-right: auto; width: 1300px; height: 400px;
justify-content: center; text-align: center; } .centered { position: absolute;
top: 50%; left: 50%; transform: translate(-50%, -50%); } .pageTitle{ color:
white; text-shadow: 5px 2px #000000; } .pageButtons{ color: white; padding: 15px
32px; text-align: center; display: inline-block; font-size: 18px; font-family:
sans-serif; margin: 4px 2px; background-color: blue; } .buttonContainer{
display: inline; padding: 25px; } .buttonText{ font-size: 20px; font-family:
sans-serif; } /*** Products Page Styles ***/ .prodHeader{ background-image:
url("images/diamonds_cropped.jpg"); margin-left: auto; margin-right: auto;
width: 1300px; height: 400px; justify-content: center; text-align: center; }
.imageGallery{ grid-template-columns: auto auto; padding: 3px; } .metalList{
display: inline-block; text-align: left; margin-right: 50px; font-family:
sans-serif; font-size: 20px; } .gemstoneList{ display: inline-block; text-align:
left; margin-left: 50px; font-family: sans-serif; font-size: 20px; } /*** About
Us Styles ***/ .aboutHeader{ background-image:
url("images/displayCase_cropped.jpg"); margin-left: auto; margin-right: auto;
width: 1300px; height: 400px; justify-content: center; text-align: center; }
.aboutUl{ text-decoration: none; font-size: 20px; text-align: center;
list-style: none; } .businessHours{ display: inline-block; margin-right: 10px; }
.aboutForm{ display:inline-block; margin-left: 10px; } label{ font-size: 20px;
font-family: sans-serif; } .formButton{ font-size: 18px; font-family:
sans-serif; padding: 15px; margin: 10px; } /*** Contact Page Styles ***/
.contactHeader{ background-image: url("images/contact_cropped.jpg");
margin-left: auto; margin-right: auto; width: 1300px; height: 400px;
justify-content: center; text-align: center; } fieldset{ max-width: 60%;
margin-left: auto; margin-right: auto; } legend{ text-align: left; font-size:
15px; font-family: sans-serif; padding: 5px; } /*** Events Page Styles ***/
.eventHeader{ background-image: url("images/event_cropped.jpg"); margin-left:
auto; margin-right: auto; width: 1300px; height: 400px; justify-content: center;
text-align: center; } table{ width: 75%; border-collapse: collapse; margin:
auto; } td, th { border: 1px solid black; text-align: left; padding: 8px;
font-family: sans-serif; } .participantPage{ text-align: center; } h2{
text-align: center; font-family: sans-serif; }
